const occupations = [
    { value: "accountant", label: "Accountant" },
    { value: "architect", label: "Architect" },
    { value: "artist", label: "Artist" },
    { value: "banker", label: "Banker" },
    { value: "business_owner", label: "Business Owner" },
    { value: "call_center_agent", label: "Call Center Agent" },
    { value: "carpenter", label: "Carpenter" },
    { value: "chef", label: "Chef" },
    { value: "construction_worker", label: "Construction Worker" },
    { value: "customer_service_representative", label: "Customer Service Representative" },
    { value: "data_analyst", label: "Data Analyst" },
    { value: "dentist", label: "Dentist" },
    { value: "doctor", label: "Doctor" },
    { value: "driver", label: "Driver" },
    { value: "electrician", label: "Electrician" },
    { value: "engineer", label: "Engineer" },
    { value: "entrepreneur", label: "Entrepreneur" },
    { value: "farmer", label: "Farmer" },
    { value: "financial_analyst", label: "Financial Analyst" },
    { value: "freelancer", label: "Freelancer" },
    { value: "graphic_designer", label: "Graphic Designer" },
    { value: "hotel_staff", label: "Hotel Staff" },
    { value: "human_resources_specialist", label: "Human Resources Specialist" },
    { value: "it_specialist", label: "IT Specialist" },
    { value: "lawyer", label: "Lawyer" },
    { value: "marketing_specialist", label: "Marketing Specialist" },
    { value: "medical_technologist", label: "Medical Technologist" },
    { value: "nurse", label: "Nurse" },
    { value: "office_clerk", label: "Office Clerk" },
    { value: "photographer", label: "Photographer" },
    { value: "pilot", label: "Pilot" },
    { value: "plumber", label: "Plumber" },
    { value: "police_officer", label: "Police Officer" },
    { value: "professor", label: "Professor" },
    { value: "programmer", label: "Programmer" },
    { value: "real_estate_agent", label: "Real Estate Agent" },
    { value: "sales_representative", label: "Sales Representative" },
    { value: "scientist", label: "Scientist" },
    { value: "security_guard", label: "Security Guard" },
    { value: "self_employed", label: "Self-Employed" },
    { value: "software_developer", label: "Software Developer" },
    { value: "student", label: "Student" },
    { value: "teacher", label: "Teacher" },
    { value: "technician", label: "Technician" },
    { value: "unemployed", label: "Unemployed" },
    { value: "waiter_waitress", label: "Waiter/Waitress" },
    { value: "web_developer", label: "Web Developer" },
    { value: "writer", label: "Writer" }
];

export default occupations;
