export const PROVINCES_PHILIPPINES = [
    { "value": "abra", "label": "Abra" },
    { "value": "agusan_del_norte", "label": "Agusan del Norte" },
    { "value": "agusan_del_sur", "label": "Agusan del Sur" },
    { "value": "aklan", "label": "Aklan" },
    { "value": "albay", "label": "Albay" },
    { "value": "antique", "label": "Antique" },
    { "value": "apayao", "label": "Apayao" },
    { "value": "aurora", "label": "Aurora" },
    { "value": "basilan", "label": "Basilan" },
    { "value": "bataan", "label": "Bataan" },
    { "value": "batanes", "label": "Batanes" },
    { "value": "batangas", "label": "Batangas" },
    { "value": "benguet", "label": "Benguet" },
    { "value": "biliran", "label": "Biliran" },
    { "value": "bohol", "label": "Bohol" },
    { "value": "bukidnon", "label": "Bukidnon" },
    { "value": "bulacan", "label": "Bulacan" },
    { "value": "cagayan", "label": "Cagayan" },
    { "value": "camarines_norte", "label": "Camarines Norte" },
    { "value": "camarines_sur", "label": "Camarines Sur" },
    { "value": "camiguin", "label": "Camiguin" },
    { "value": "capiz", "label": "Capiz" },
    { "value": "catanduanes", "label": "Catanduanes" },
    { "value": "cavite", "label": "Cavite" },
    { "value": "cebu", "label": "Cebu" },
    { "value": "cotabato", "label": "Cotabato" },
    { "value": "davao_de_oro", "label": "Davao de Oro" },
    { "value": "davao_del_norte", "label": "Davao del Norte" },
    { "value": "davao_del_sur", "label": "Davao del Sur" },
    { "value": "davao_occidental", "label": "Davao Occidental" },
    { "value": "davao_oriental", "label": "Davao Oriental" },
    { "value": "dinagat_islands", "label": "Dinagat Islands" },
    { "value": "eastern_samar", "label": "Eastern Samar" },
    { "value": "guimaras", "label": "Guimaras" },
    { "value": "ifugao", "label": "Ifugao" },
    { "value": "ilocos_norte", "label": "Ilocos Norte" },
    { "value": "ilocos_sur", "label": "Ilocos Sur" },
    { "value": "iloilo", "label": "Iloilo" },
    { "value": "isabela", "label": "Isabela" },
    { "value": "kalinga", "label": "Kalinga" },
    { "value": "la_union", "label": "La Union" },
    { "value": "laguna", "label": "Laguna" },
    { "value": "lanao_del_norte", "label": "Lanao del Norte" },
    { "value": "lanao_del_sur", "label": "Lanao del Sur" },
    { "value": "leyte", "label": "Leyte" },
    { "value": "maguindanao_del_norte", "label": "Maguindanao del Norte" },
    { "value": "maguindanao_del_sur", "label": "Maguindanao del Sur" },
    { "value": "marinduque", "label": "Marinduque" },
    { "value": "masbate", "label": "Masbate" },
    { "value": "misamis_occidental", "label": "Misamis Occidental" },
    { "value": "misamis_oriental", "label": "Misamis Oriental" },
    { "value": "mountain_province", "label": "Mountain Province" },
    { "value": "negros_occidental", "label": "Negros Occidental" },
    { "value": "negros_oriental", "label": "Negros Oriental" },
    { "value": "northern_samar", "label": "Northern Samar" },
    { "value": "nueva_ecija", "label": "Nueva Ecija" },
    { "value": "nueva_vizcaya", "label": "Nueva Vizcaya" },
    { "value": "occidental_mindoro", "label": "Occidental Mindoro" },
    { "value": "oriental_mindoro", "label": "Oriental Mindoro" },
    { "value": "palawan", "label": "Palawan" },
    { "value": "pampanga", "label": "Pampanga" },
    { "value": "pangasinan", "label": "Pangasinan" },
    { "value": "quezon", "label": "Quezon" },
    { "value": "quirino", "label": "Quirino" },
    { "value": "rizal", "label": "Rizal" },
    { "value": "romblon", "label": "Romblon" },
    { "value": "samar", "label": "Samar" },
    { "value": "sarangani", "label": "Sarangani" },
    { "value": "siquijor", "label": "Siquijor" },
    { "value": "sorsogon", "label": "Sorsogon" },
    { "value": "south_cotabato", "label": "South Cotabato" },
    { "value": "southern_leyte", "label": "Southern Leyte" },
    { "value": "sultan_kudarat", "label": "Sultan Kudarat" },
    { "value": "sulu", "label": "Sulu" },
    { "value": "surigao_del_norte", "label": "Surigao del Norte" },
    { "value": "surigao_del_sur", "label": "Surigao del Sur" },
    { "value": "tarlac", "label": "Tarlac" },
    { "value": "tawi_tawi", "label": "Tawi-Tawi" },
    { "value": "zambales", "label": "Zambales" },
    { "value": "zamboanga_del_norte", "label": "Zamboanga del Norte" },
    { "value": "zamboanga_del_sur", "label": "Zamboanga del Sur" },
    { "value": "zamboanga_sibugay", "label": "Zamboanga Sibugay" },
    { "value": "metro_manila", "label": "Metro Manila" },
    { "value": "manila", "label": "Manila" },
    { "value": "quezon_city", "label": "Quezon City" },
    { "value": "caloocan", "label": "Caloocan" },
    { "value": "las_pinas", "label": "Las Piñas" },
    { "value": "makati", "label": "Makati" },
    { "value": "malabon", "label": "Malabon" },
    { "value": "mandaluyong", "label": "Mandaluyong" },
    { "value": "marikina", "label": "Marikina" },
    { "value": "muntinlupa", "label": "Muntinlupa" },
    { "value": "navotas", "label": "Navotas" },
    { "value": "paranaque", "label": "Parañaque" },
    { "value": "pasay", "label": "Pasay" },
    { "value": "pasig", "label": "Pasig" },
    { "value": "san_juan", "label": "San Juan" },
    { "value": "taguig", "label": "Taguig" },
    { "value": "valenzuela", "label": "Valenzuela" }
];
